[project]
name = "wyoming-supertonic-docker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.1",
    "onnxruntime>=1.23.2",
    "sentence-stream>=1.3.0",
    "wyoming>=1.8.0",
]
